In [3]:
import pandas as pd
# df = pd.read_csv("../datasets/daraz_dataset.csv")

# print(df.shape)
print(df.columns)
# print(df.info())
# print(df["TotalAmount"].max())
# print(df["TotalAmount"].min())
# print(df["TotalAmount"].mean())   
# print(df[["CustomerName", "District", "TotalAmount"]])
# print(df.iloc[11]) # 11th number index of row lae retrive garyo
# print(df.iloc[0:5])
# print(df.iloc[0, 2]) # to catch a specific cell
# print(df.iloc[:, [2, 6, 8]]) # to retrieve particular column or multiple columns
# print(df.iloc[-1])

# print(df.loc[:, ["CustomerName", "District"]])
# print(df[df["District"] == "Kathmandu"]) 
# print(df.loc[df["District"] == "Kathmandu"])
# print(df.loc[df["TotalAmount"] > 30000])

# Filter chaining --> kathmandu district bata esewa payment method used
# print(df[(df["District"] == "Kathmandu") & (df["PaymentMethod"] == "eSewa")])
# print(df[(df["Category"] == "Electronics") & (df["Rating"] == 5)])
# print(df.sort_values("TotalAmount", ascending = False))

NameError: name 'df' is not defined

In [60]:
# Cleaning the bad data
df = pd.read_csv("../datasets/bad_daraz_dataset.csv")
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [20]:
# df.isnull().sum() # NaN missing values datatypes catch and sum
# df.fillna(0) # Add 0 to NaN values
df["price"] = pd.to_numeric(df["price"], errors = "coerce")
df["price"] = df["price"].fillna(df["price"].mean())
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [21]:
df["age"] = pd.to_numeric(df["age"], errors = "coerce")
df["age"] = df["age"].fillna(df["age"].median())
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [22]:
# df.dropna()
# df[df.duplicated()]

# remove "%" 
df["discount_percent"] = df["discount_percent"].replace("%", "")
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [28]:
# Cleaning a dublicate data
# df.duplicated().sum() # returns the count of duplicates in the dataset
df[df.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [34]:
# Partial Duplicacy (in a particular column
df.duplicated("product_id").sum()

np.int64(2)

In [41]:
# removes row with complete duplication
df.drop_duplicates(inplace=True)
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [1]:
# partial duplicay
df.drop_duplicates(subset="product_id", inplace = True)
df

NameError: name 'df' is not defined

In [53]:
# Finding the neagtive values
# df["price"] = pd.to_numeric(df["price"], errors = "coerce")
# df[df["price"] < 0]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [4]:
# finding abnormal rating that is 5
# df["rating"] = pd.to_numeric(df["rating"], errors = "coerce")
# df[df["rating"] > 5]

# making the neagtive price to 0
# df.loc[df["price"] < 0, "price"] = 0
# df

df = df[df["price"] > 0 ]

NameError: name 'df' is not defined

In [66]:
print(df)
# df["city"] = df["city"].str.lstrip() # removes space from left side 
# df["city"] = df["city"].str.rstrip() # removes space from right side
# df

    product_id product_name     category  price discount_percent  rating  \
0            1       Laptop  Electronics  75000               10     4.8
1            2        Phone  Electronics    NaN               15     4.6
2            3        Shoes      Fashion   3500               5%     4.2
3            4      T-Shirt      Fashion   1500               20     NaN
4            5        Watch  Accessories   5500               10     4.5
5            6   Headphones  Electronics   4200              NaN     4.1
6            7       Laptop  Electronics  75000               10     4.8
7            8          Bag      Fashion    abc               12     3.9
8            9        Mouse  Electronics   1800                5     4.3
9            9          Cup  Electronics   1800                5     4.3
10          10     Keyboard  Electronics   2500                5     4.4
11          10         Haha  Electronics   2500                5     4.4
12          11       Bottle         Home    800                0     5.5
13          12        Chair    Furniture  -2500               10     4.0
14          12        Chair    Furniture  -2500               10     4.0

           stock       seller        city      brand gender_target      age  \
0             25      TechHub   Kathmandu       Dell        Unisex       25
1             40  GadgetNepal     Pokhara    Samsung        Unisex       30
2             60   FashionHub     Itahari       Nike          Male       22
3            150        Style  Biratnagar     Adidas        Female   Female
4   Out of Stock        TimeX   Kathmandu      Casio          Male       28
5             75     AudioPro     Pokhara        JBL        Unisex      24
6             25      TechHub   Kathmandu       Dell        Unisex       25
7             45     CarryAll      Dharan  Wildcraft        Female       19
8            NaN      TechHub   Kathmandu   Logitech        Unisex      NaN
9            NaN      TechHub   Kathmandu   Logitech        Unisex      NaN
10            35     TechHub    Kathmandu   Logitech        Unisex       21
11            35     TechHub    Kathmandu   Logitech        Unisex       21
12           100    HomeStore    Janakpur    Generic        Unisex       26
13            -5      FurniCo    Lalitpur       IKEA        Unisex  Unknown
14            -5      FurniCo    Lalitpur       IKEA        Unisex  Unknown

    reviews
0       120
1       210
2        55
3        30
4        80
5        65
6       120
7        18
8        90
9        90
10      110
11      110
12       12
13       44
14       44

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [72]:
# df["city"] = df["city"].str.lower()
# df["city"] = df["city"].str.upper()
df["city"] = df["city"].str.title() # only fist letter capital or upper
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [13]:
# Example of Outlier Detection (IQR method)
df = pd.DataFrame({
    "salary" : [1000, 2000, 3000, 5000, 7000, 8000, 9000, 12000, 50000]
})

# quartiles
median = df["salary"].quantile(0.5)
first_quartile = df["salary"].quantile(0.25)
third_quartile = df["salary"].quantile(0.75)

# IQR 
iqr = third_quartile - first_quartile
lower_bound = first_quartile - (1.5 * iqr)
upper_bound = third_quartile + (1.5 * iqr)
lower_bound, upper_bound

(np.float64(-6000.0), np.float64(18000.0))

In [14]:
outliers = df[(df["salary"] < -5500) | (df["salary"] > 16500)]
print(outliers)

   salary
8   50000